apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base  
namespace: webapp-dev
namePrefix: dev-
labels:
  - includeSelectors: true
    pairs:
      environment: development
      version: latest