name: Test Kustomize Configurations
on:
  push:
    branches: [ main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Test base Configuration   
        run: |
          kubectl kustomize ./base
  
  